os: linux
dist: xenial
language: python
python:
- 3.6
- 3.7
- 3.8
- 3.9
- pypy3
addons:
  apt:
    packages:
    - libmms0
jobs:
  include:
    - os: osx
      # Not required but makes Travis' output prettier
      language: generic
      env: MB_PYTHON_VERSION=3.6
    - os: osx
      language: generic
      env: MB_PYTHON_VERSION=3.7
    - os: osx
      language: generic
      env: MB_PYTHON_VERSION=3.8
    - os: osx
      language: generic
      env: MB_PYTHON_VERSION=3.9
before_install: |
  if [ $TRAVIS_OS_NAME == osx ]; then
    git clone https://github.com/matthew-brett/multibuild
    touch config.sh # required by the multibuild project
    source multibuild/common_utils.sh
    source multibuild/travis_steps.sh
    before_install
    curl https://mediaarea.net/download/binary/libmediainfo0/${MEDIAINFO_VERSION}/MediaInfo_DLL_${MEDIAINFO_VERSION}_Mac_i386+x86_64.tar.bz2 | tar xj MediaInfoLib/libmediainfo.0.dylib MediaInfoLib/License.html
    mv MediaInfoLib/libmediainfo.0.dylib pymediainfo
    mv MediaInfoLib/License.html docs
  else
    pushd /tmp
    libzen_deb=libzen0v5_${LIBZEN_VERSION}-1_amd64.xUbuntu_${UBUNTU_VERSION}.deb
    mediainfo_deb=libmediainfo0v5_${MEDIAINFO_VERSION}-1_amd64.xUbuntu_${UBUNTU_VERSION}.deb
    curl -O https://mediaarea.net/download/binary/libzen0/${LIBZEN_VERSION}/${libzen_deb}
    curl -O https://mediaarea.net/download/binary/libmediainfo0/${MEDIAINFO_VERSION}/${mediainfo_deb}
    sudo dpkg -i ${libzen_deb} ${mediainfo_deb}
    popd
  fi
  pip install pytest setuptools_scm
  python setup.py install
script: pytest
notifications:
  email:
    on_success: change
    on_failure: change
after_success: |
  if [[ $TRAVIS_TAG ]]; then
    if [[ $TRAVIS_OS_NAME == osx && $MB_PYTHON_VERSION == $PYTHON_DEPLOY_VERSION ]]; then
      python setup.py bdist_wheel
      pip install twine
      twine upload --skip-existing -u sbraz dist/*.{whl,gz}
    elif [[ $TRAVIS_OS_NAME == linux && $TRAVIS_PYTHON_VERSION == $PYTHON_DEPLOY_VERSION ]]; then
      # sdists generated on OSX have a problem with the accented test file
      # https://github.com/sbraz/pymediainfo/issues/67
      python setup.py sdist
      pip install twine
      twine upload --skip-existing -u sbraz dist/*.{whl,gz}
    fi
  fi
env:
  global:
    # TWINE_PASSWORD
    - secure: "WjxnZjhgG7SCFbtYNbCAv935y3GG1CBHKJZbjSag9dBNg41OF98Q4PjnK6KxQ68Avfsv8mTGn8FbbGyXU4J033khynMCDOPMo0MAKPVYTaon3GKXf9triyzuuFty5U0kydJyqQdiqpkJPgkOou19s/x1AesfBthUswS51kyWdeg="
    - MEDIAINFO_VERSION: 20.09
    - LIBZEN_VERSION: 0.4.38
    - UBUNTU_VERSION: 16.04
    - PYTHON_DEPLOY_VERSION: 3.8
