os: linux
dist: bionic
language: python
addons:
  apt:
    packages:
    - libmms0
jobs:
  include:
    - python: &python_main_version 3.8
      env:
        TOXENV: docs,black,flake8,isort,mypy,pylint
        TOX_PARALLEL: "-p"
   
    
before_install: |
  if [ $TRAVIS_OS_NAME == osx ]; then
    git clone https://github.com/matthew-brett/multibuild
    touch config.sh # required by the multibuild project
    source multibuild/common_utils.sh
    source multibuild/travis_steps.sh
    before_install
    curl https://mediaarea.net/download/binary/libmediainfo0/${MEDIAINFO_VERSION}/MediaInfo_DLL_${MEDIAINFO_VERSION}_Mac_i386+x86_64.tar.bz2 | tar xj MediaInfoLib/libmediainfo.0.dylib MediaInfoLib/License.html
    # Required for tests to pass with tox
    cp MediaInfoLib/libmediainfo.0.dylib /usr/local/lib
    mv MediaInfoLib/libmediainfo.0.dylib pymediainfo
    mv MediaInfoLib/License.html docs
  else
    pushd /tmp
    libzen_deb=libzen0v5_${LIBZEN_VERSION}-1_amd64.xUbuntu_${UBUNTU_VERSION}.deb
    mediainfo_deb=libmediainfo0v5_${MEDIAINFO_VERSION}-1_amd64.xUbuntu_${UBUNTU_VERSION}.deb
    curl -O https://mediaarea.net/download/binary/libzen0/${LIBZEN_VERSION}/${libzen_deb}
    curl -O https://mediaarea.net/download/binary/libmediainfo0/${MEDIAINFO_VERSION}/${mediainfo_deb}
    sudo dpkg -i ${libzen_deb} ${mediainfo_deb}
    popd
  fi
  pip install tox
script: "tox $TOX_PARALLEL"
notifications:
  email:
    on_success: change
    on_failure: change

  fi
env:
  global:
    # TWINE_PASSWORD
    - secure: "WjxnZjhgG7SCFbtYNbCAv935y3GG1CBHKJZbjSag9dBNg41OF98Q4PjnK6KxQ68Avfsv8mTGn8FbbGyXU4J033khynMCDOPMo0MAKPVYTaon3GKXf9triyzuuFty5U0kydJyqQdiqpkJPgkOou19s/x1AesfBthUswS51kyWdeg="
    - MEDIAINFO_VERSION: 21.03
    - LIBZEN_VERSION: 0.4.39
    - UBUNTU_VERSION: 18.04
    - PYTHON_MAIN_VERSION: *python_main_version
    - TOX_PARALLEL_NO_SPINNER: 1
