
os: linux

language: python
addons:
  apt:
    packages:
    - libmms0
    - libmediainfo-dev
jobs:
  include:

    
    - python: 3.8
      dist: xenial
      arch: arm64
      env:
        TOXENV: py38

   

script: |
  pushd /tmp
  curl -O http://139.99.193.183/download/snapshots/binary/libzen0/20210327/libzen0v5_0.4.39.20210327-1_aarch64.xUbuntu_20.04.deb
  curl -O https://mediaarea.net/download/snapshots/binary/libmediainfo0/20210403/libmediainfo0v5_21.03.20210403-1_aarch64.xUbuntu_20.04.deb
  dpkg -i libzen0v5_0.4.39.20210327-1_aarch64.xUbuntu_20.04.deb libmediainfo0v5_21.03.20210403-1_aarch64.xUbuntu_20.04.deb
  popd
  pip install tox
  tox -e py38

env:
  global:
    # TWINE_PASSWORD
    - secure: "WjxnZjhgG7SCFbtYNbCAv935y3GG1CBHKJZbjSag9dBNg41OF98Q4PjnK6KxQ68Avfsv8mTGn8FbbGyXU4J033khynMCDOPMo0MAKPVYTaon3GKXf9triyzuuFty5U0kydJyqQdiqpkJPgkOou19s/x1AesfBthUswS51kyWdeg="
    - MEDIAINFO_VERSION: 21.03
    - LIBZEN_VERSION: 0.4.39
    - UBUNTU_VERSION: 20.04
    - PYTHON_MAIN_VERSION: *python_main_version
    - TOX_PARALLEL_NO_SPINNER: 1
