
os: linux

language: python
addons:
  apt:
    packages:
    - libmms0
    - libmediainfo-dev
jobs:
  include:

    
    - python: 3.8
      dist: xenial
      arch: arm64
      env:
        TOXENV: py38

   

script: |

  pip install tox
  tox -p

env:
  global:
    # TWINE_PASSWORD
    - secure: "WjxnZjhgG7SCFbtYNbCAv935y3GG1CBHKJZbjSag9dBNg41OF98Q4PjnK6KxQ68Avfsv8mTGn8FbbGyXU4J033khynMCDOPMo0MAKPVYTaon3GKXf9triyzuuFty5U0kydJyqQdiqpkJPgkOou19s/x1AesfBthUswS51kyWdeg="
    - MEDIAINFO_VERSION: 21.03
    - LIBZEN_VERSION: 0.4.39
    - UBUNTU_VERSION: 20.04
    - PYTHON_MAIN_VERSION: *python_main_version
    - TOX_PARALLEL_NO_SPINNER: 1
