
os: linux

language: python
addons:
  apt:
    packages:
    - libmms0
jobs:
  include:

    - python: 3.8
      dist: bionic
      arch: amd64
      env:
        TOXENV: py38
    
    - python: 3.8
      dist: xenial
      arch: arm64
      env:
        TOXENV: py38

   
before_install: |
  if [ $TRAVIS_OS_NAME == arm64 ]; then
    pushd /tmp
    libzen_deb=libzen0v5_0.4.39-1_arm64.xUbuntu_18.04.deb
    mediainfo_deb=libmediainfo0v5_21.03.20210403-1_aarch64.xUbuntu_20.04.deb
    curl -O https://mediaarea.net/download/binary/libzen0/${LIBZEN_VERSION}/${libzen_deb}
    curl -O https://mediaarea.net/download/binary/libmediainfo0/${MEDIAINFO_VERSION}/${mediainfo_deb}
    sudo dpkg -i ${libzen_deb} ${mediainfo_deb}
    popd
  else
    pushd /tmp
    libzen_deb=libzen0v5_${LIBZEN_VERSION}-1_amd64.xUbuntu_${UBUNTU_VERSION}.deb
    mediainfo_deb=libmediainfo0v5_${MEDIAINFO_VERSION}-1_amd64.xUbuntu_${UBUNTU_VERSION}.deb
    curl -O https://mediaarea.net/download/binary/libzen0/${LIBZEN_VERSION}/${libzen_deb}
    curl -O https://mediaarea.net/download/binary/libmediainfo0/${MEDIAINFO_VERSION}/${mediainfo_deb}
    sudo dpkg -i ${libzen_deb} ${mediainfo_deb}
    popd
  fi
  pip install tox
script: "tox $TOX_PARALLEL"
notifications:
  email:
    on_success: change
    on_failure: change
after_success: |
  if [[ $TRAVIS_TAG ]]; then
    if [[ $TRAVIS_OS_NAME == osx && $MB_PYTHON_VERSION == $PYTHON_MAIN_VERSION ]]; then
      pip install wheel twine
      python setup.py bdist_wheel
      twine upload --skip-existing -u sbraz dist/*.whl
    # We only want to upload distributions from environments where
    # the actual test suite runs, and not just QA stuff like pylint & friends,
    # so we make sure it's a py-something tox environment
    elif [[ $TRAVIS_OS_NAME == linux && $TRAVIS_PYTHON_VERSION == $PYTHON_MAIN_VERSION && $TOXENV == py?? ]]; then
      # sdists generated on OSX have a problem with the accented test file
      # https://github.com/sbraz/pymediainfo/issues/67
      python setup.py sdist
      pip install twine
      twine upload --skip-existing -u sbraz dist/*.gz
    fi
  fi
env:
  global:
    # TWINE_PASSWORD
    - secure: "WjxnZjhgG7SCFbtYNbCAv935y3GG1CBHKJZbjSag9dBNg41OF98Q4PjnK6KxQ68Avfsv8mTGn8FbbGyXU4J033khynMCDOPMo0MAKPVYTaon3GKXf9triyzuuFty5U0kydJyqQdiqpkJPgkOou19s/x1AesfBthUswS51kyWdeg="
    - MEDIAINFO_VERSION: 21.03
    - LIBZEN_VERSION: 0.4.39
    - UBUNTU_VERSION: 18.04
    - PYTHON_MAIN_VERSION: *python_main_version
    - TOX_PARALLEL_NO_SPINNER: 1
