
os: linux

language: python
addons:
  apt:
    packages:
    - libmms0
jobs:
  include:

    
    - python: 3.8
      dist: xenial
      arch: arm64
      env:
        TOXENV: py38

   
before_install: |
  pushd /tmp
  libzen_deb=libzen0v5_0.4.39-1_arm64.xUbuntu_18.04.deb
  mediainfo_deb=libmediainfo0v5_21.03.20210403-1_aarch64.xUbuntu_20.04.deb
  curl -O https://mediaarea.net/download/binary/libzen0/${LIBZEN_VERSION}/${libzen_deb}
  curl -O https://mediaarea.net/download/binary/libmediainfo0/${MEDIAINFO_VERSION}/${mediainfo_deb}
  sudo dpkg -i ${libzen_deb} ${mediainfo_deb}
  popd
  pip install tox
script: "tox $TOX_PARALLEL"
notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    # TWINE_PASSWORD
    - secure: "WjxnZjhgG7SCFbtYNbCAv935y3GG1CBHKJZbjSag9dBNg41OF98Q4PjnK6KxQ68Avfsv8mTGn8FbbGyXU4J033khynMCDOPMo0MAKPVYTaon3GKXf9triyzuuFty5U0kydJyqQdiqpkJPgkOou19s/x1AesfBthUswS51kyWdeg="
    - MEDIAINFO_VERSION: 21.03
    - LIBZEN_VERSION: 0.4.39
    - UBUNTU_VERSION: 18.04
    - PYTHON_MAIN_VERSION: *python_main_version
    - TOX_PARALLEL_NO_SPINNER: 1
